language: lua

env:
  #- LUAJIT_VERSION="v2.1" LUAJIT_BIN="luajit-2.1.0-alpha" PTHREAD="libpthread.so.0"
  - LUAJIT_VERSION="master" LUAJIT_BIN="luajit" PTHREAD="libpthread.so.0"

compiler:
  - gcc

before_script:
  - sudo mkdir -p /usr/local/share/lua/5.1/
  - sudo chmod -R 777 /usr/local

script: "sudo LUAJIT_VERSION=$LUAJIT_VERSION bash test/tools/travis_install.sh && LD_PRELOAD=$PTHREAD $LUAJIT_BIN test.lua"

branches:
  only:
    - master
    - feature/travis_ci

install:
  - sudo apt-get install luarocks

notifications:
  recipients:
    - iyatomi+pulpo.test@gmail.com
  email:
    on_success: change
    on_failure: always

